name: Push To Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run Docker Compose
      run: | 
        docker-compose up -d
        docker exec auth_server npm run test
      env:
        CI: true